### ISSUE TITLE
The button goes off the screen at the bottom

### ISSUE THREAD

**Issue by PaulDMendoza** [MobProgramming/MobTimer.Python#4]
![image](https://cloud.githubusercontent.com/assets/1039795/12424605/ce63cbc2-be85-11e5-8603-534e0081fd7e.png)

I also don't see my logo.

**Comment by DeadlyApps** [comment]
This is related to operating system zoom/dpi settings. Something will need to be done regarding the proper scaling when the operating system is zoomin in on the fonts.

**Comment by DeadlyApps** [comment]
Logo view is configured in the config file. You need to set the display logo setting to true

**Comment by DeadlyApps** [comment]
This will no longer happen. Screens now dynamically scale regardless of zooming or resolution
