### ISSUE TITLE
Doesn't allow me to go back to the menu for the mob timer (alt used to work in the .NET version)

### ISSUE THREAD

**Issue by PaulDMendoza** [MobProgramming/MobTimer.Python#5]
The old mob timer let me go to the mob menu mid-time and reconfigure things. This one doesn't let me do that. I had to go to my task manager and kill it and then restart it. When trying to configure things like themes that is a real pain or if we need to make one small tweak to the settings. 

Also, I can't quit the app once I'm on the configuration screen from what I can tell.

**Comment by DeadlyApps** [comment]
The Mob Timer is session based. You simply re-launch the executable to stop the timer mid time. Check your operating systems zoom/dpi settings, you might be hiding the quit button.

Here is what your timer should look like when you are looking at the main screen blocker.
https://twitter.com/ChristophLucian/status/685706314140368896
